# Generated by Django 5.2.9 on 2025-12-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabTestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinical", "Клинические"),
                            ("biochemical", "Биохимические"),
                            ("hormonal", "Гормональные"),
                            ("immunological", "Иммунологические"),
                            ("microbiological", "Микробиологические"),
                            ("cytological", "Цитологические"),
                            ("genetic", "Генетические"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Единицы измерения"
                    ),
                ),
                (
                    "normal_range",
                    models.CharField(blank=True, max_length=100, verbose_name="Норма"),
                ),
                (
                    "preparation",
                    models.TextField(
                        blank=True, verbose_name="Подготовка к исследованию"
                    ),
                ),
                (
                    "turnaround_time",
                    models.PositiveIntegerField(
                        default=24, verbose_name="Срок выполнения (часов)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Тип исследования",
                "verbose_name_plural": "Типы исследований",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyStudyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("xray", "Рентген"),
                            ("ct", "КТ"),
                            ("mri", "МРТ"),
                            ("us", "УЗИ"),
                            ("mammo", "Маммография"),
                            ("fluoro", "Флюорография"),
                            ("angio", "Ангиография"),
                        ],
                        max_length=20,
                        verbose_name="Модальность",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        max_length=100, verbose_name="Область исследования"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "preparation",
                    models.TextField(blank=True, verbose_name="Подготовка"),
                ),
                (
                    "contraindications",
                    models.TextField(blank=True, verbose_name="Противопоказания"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Длительность (минут)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Тип радиологического исследования",
                "verbose_name_plural": "Типы радиологических исследований",
                "ordering": ["modality", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создано"),
                            ("sample_collected", "Биоматериал собран"),
                            ("in_progress", "В работе"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Плановое"),
                            ("urgent", "Срочное"),
                            ("stat", "Cito!"),
                        ],
                        default="routine",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "clinical_info",
                    models.TextField(blank=True, verbose_name="Клиническая информация"),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Диагноз"
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата направления"
                    ),
                ),
                (
                    "sample_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата забора"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата выполнения"
                    ),
                ),
                (
                    "ordering_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_lab_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Направивший врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="registry.patient",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "test_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="laboratory.labtesttype",
                        verbose_name="Тип исследования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление на исследование",
                "verbose_name_plural": "Направления на исследования",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Результат")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="Единицы"),
                ),
                (
                    "reference_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Референсный диапазон"
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(
                        default=False, verbose_name="Отклонение от нормы"
                    ),
                ),
                (
                    "interpretation",
                    models.TextField(blank=True, verbose_name="Интерпретация"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="Комментарии")),
                (
                    "result_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата результата"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="laboratory.laborder",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_lab_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выполнил",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_lab_tests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подтвердил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат исследования",
                "verbose_name_plural": "Результаты исследований",
            },
        ),
        migrations.CreateModel(
            name="RadiologyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланировано"),
                            ("in_progress", "Выполняется"),
                            ("completed", "Выполнено"),
                            ("described", "Описано"),
                            ("cancelled", "Отменено"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Плановое"),
                            ("urgent", "Срочное"),
                            ("stat", "Cito!"),
                        ],
                        default="routine",
                        max_length=20,
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "clinical_info",
                    models.TextField(blank=True, verbose_name="Клиническая информация"),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Диагноз"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата назначена"
                    ),
                ),
                (
                    "performed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата выполнения"
                    ),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата направления"
                    ),
                ),
                (
                    "ordering_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_radiology_studies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Направивший врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiology_orders",
                        to="registry.patient",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "study_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="laboratory.radiologystudytype",
                        verbose_name="Тип исследования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление на рад. исследование",
                "verbose_name_plural": "Направления на рад. исследования",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="DicomStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "study_instance_uid",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Study Instance UID"
                    ),
                ),
                ("study_date", models.DateTimeField(verbose_name="Дата исследования")),
                (
                    "accession_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Accession Number"
                    ),
                ),
                (
                    "modality",
                    models.CharField(max_length=20, verbose_name="Модальность"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Описание"
                    ),
                ),
                (
                    "number_of_series",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество серий"
                    ),
                ),
                (
                    "number_of_images",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество изображений"
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Путь к файлам"
                    ),
                ),
                ("pacs_url", models.URLField(blank=True, verbose_name="URL в PACS")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "radiology_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dicom_studies",
                        to="laboratory.radiologyorder",
                        verbose_name="Направление",
                    ),
                ),
            ],
            options={
                "verbose_name": "DICOM исследование",
                "verbose_name_plural": "DICOM исследования",
                "ordering": ["-study_date"],
            },
        ),
        migrations.CreateModel(
            name="RadiologyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("findings", models.TextField(verbose_name="Протокол исследования")),
                ("conclusion", models.TextField(verbose_name="Заключение")),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Рекомендации"),
                ),
                (
                    "report_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата заключения"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="laboratory.radiologyorder",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "radiologist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiology_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач-рентгенолог",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат рад. исследования",
                "verbose_name_plural": "Результаты рад. исследований",
            },
        ),
    ]
