# Generated by Django 5.2.9 on 2025-12-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExaminationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название шаблона"),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Специализация"
                    ),
                ),
                ("complaints", models.TextField(blank=True, verbose_name="Жалобы")),
                ("anamnesis", models.TextField(blank=True, verbose_name="Анамнез")),
                (
                    "examination_plan",
                    models.TextField(blank=True, verbose_name="План осмотра"),
                ),
                (
                    "diagnosis_template",
                    models.TextField(blank=True, verbose_name="Шаблон диагноза"),
                ),
                (
                    "recommendations_template",
                    models.TextField(blank=True, verbose_name="Шаблон рекомендаций"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный шаблон"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examination_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон осмотра",
                "verbose_name_plural": "Шаблоны осмотров",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер карты"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record",
                        to="registry.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медицинская карта",
                "verbose_name_plural": "Медицинские карты",
            },
        ),
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата осмотра"
                    ),
                ),
                ("complaints", models.TextField(blank=True, verbose_name="Жалобы")),
                (
                    "anamnesis",
                    models.TextField(blank=True, verbose_name="Анамнез заболевания"),
                ),
                (
                    "life_anamnesis",
                    models.TextField(blank=True, verbose_name="Анамнез жизни"),
                ),
                (
                    "general_condition",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Общее состояние"
                    ),
                ),
                (
                    "consciousness",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Сознание"
                    ),
                ),
                ("skin", models.TextField(blank=True, verbose_name="Кожные покровы")),
                (
                    "lymph_nodes",
                    models.TextField(blank=True, verbose_name="Лимфатические узлы"),
                ),
                (
                    "respiratory_system",
                    models.TextField(blank=True, verbose_name="Органы дыхания"),
                ),
                (
                    "cardiovascular_system",
                    models.TextField(
                        blank=True, verbose_name="Сердечно-сосудистая система"
                    ),
                ),
                (
                    "digestive_system",
                    models.TextField(blank=True, verbose_name="Органы пищеварения"),
                ),
                (
                    "urinary_system",
                    models.TextField(
                        blank=True, verbose_name="Мочевыделительная система"
                    ),
                ),
                (
                    "nervous_system",
                    models.TextField(blank=True, verbose_name="Нервная система"),
                ),
                (
                    "musculoskeletal_system",
                    models.TextField(
                        blank=True, verbose_name="Опорно-двигательный аппарат"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Температура",
                    ),
                ),
                (
                    "blood_pressure_sys",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="АД систолическое"
                    ),
                ),
                (
                    "blood_pressure_dia",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="АД диастолическое"
                    ),
                ),
                (
                    "pulse",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Пульс"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ЧДД"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Рост (см)",
                    ),
                ),
                (
                    "diagnosis_preliminary",
                    models.TextField(
                        blank=True, verbose_name="Предварительный диагноз"
                    ),
                ),
                (
                    "diagnosis_main",
                    models.TextField(blank=True, verbose_name="Основной диагноз"),
                ),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Код МКБ-10"
                    ),
                ),
                (
                    "diagnosis_concomitant",
                    models.TextField(blank=True, verbose_name="Сопутствующий диагноз"),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Рекомендации"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examination",
                        to="registry.appointment",
                        verbose_name="Приём",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examinations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examinations",
                        to="emr.medicalrecord",
                        verbose_name="Медицинская карта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Осмотр",
                "verbose_name_plural": "Осмотры",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prescription_type",
                    models.CharField(
                        choices=[
                            ("medication", "Лекарственное средство"),
                            ("procedure", "Процедура"),
                            ("consultation", "Консультация"),
                            ("diet", "Диета"),
                            ("regime", "Режим"),
                        ],
                        max_length=20,
                        verbose_name="Тип назначения",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "dosage",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Дозировка"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Частота приёма"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Длительность"
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Способ применения"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Инструкции"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активно"),
                            ("completed", "Выполнено"),
                            ("cancelled", "Отменено"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="emr.examination",
                        verbose_name="Осмотр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение",
                "verbose_name_plural": "Назначения",
                "ordering": ["-created_at"],
            },
        ),
    ]
