# Generated by Django 5.2.9 on 2025-12-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория препаратов",
                "verbose_name_plural": "Категории препаратов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Торговое название"),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="МНН (INN)"
                    ),
                ),
                (
                    "drug_type",
                    models.CharField(
                        choices=[
                            ("essential", "ЖНВЛП"),
                            ("regular", "Обычное"),
                            ("narcotic", "Наркотическое"),
                            ("psychotropic", "Психотропное"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="Тип препарата",
                    ),
                ),
                (
                    "form",
                    models.CharField(max_length=100, verbose_name="Форма выпуска"),
                ),
                ("dosage", models.CharField(max_length=100, verbose_name="Дозировка")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Производитель"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Страна"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Штрих-код"
                    ),
                ),
                (
                    "atc_code",
                    models.CharField(blank=True, max_length=20, verbose_name="Код АТХ"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "contraindications",
                    models.TextField(blank=True, verbose_name="Противопоказания"),
                ),
                (
                    "storage_conditions",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Условия хранения"
                    ),
                ),
                (
                    "is_prescription",
                    models.BooleanField(default=False, verbose_name="По рецепту"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drugs",
                        to="pharmacy.drugcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лекарственное средство",
                "verbose_name_plural": "Лекарственные средства",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DrugRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        max_length=200, verbose_name="Отделение/подразделение"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("submitted", "Подана"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                            ("fulfilled", "Выполнена"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_drug_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Утвердил",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заявитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на препараты",
                "verbose_name_plural": "Заявки на препараты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DrugRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_requested",
                    models.PositiveIntegerField(verbose_name="Запрошено"),
                ),
                (
                    "quantity_approved",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Одобрено"
                    ),
                ),
                (
                    "quantity_issued",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Выдано"
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_items",
                        to="pharmacy.drug",
                        verbose_name="Препарат",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.drugrequest",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заявки",
                "verbose_name_plural": "Позиции заявки",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Расположение"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Приход"),
                            ("issue", "Расход"),
                            ("transfer", "Перемещение"),
                            ("write_off", "Списание"),
                            ("return", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип движения",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер партии"
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер документа"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Основание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="pharmacy.drug",
                        verbose_name="Препарат",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Выполнил",
                    ),
                ),
                (
                    "warehouse_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_out",
                        to="pharmacy.warehouse",
                        verbose_name="Склад-источник",
                    ),
                ),
                (
                    "warehouse_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements_in",
                        to="pharmacy.warehouse",
                        verbose_name="Склад-получатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Движение товара",
                "verbose_name_plural": "Движения товаров",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DrugStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=100, verbose_name="Номер партии"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "unit",
                    models.CharField(
                        default="шт", max_length=20, verbose_name="Единица измерения"
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена закупки"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Цена продажи",
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата производства"
                    ),
                ),
                ("expiry_date", models.DateField(verbose_name="Срок годности")),
                (
                    "received_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата поступления"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Поставщик"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Номер накладной"
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="pharmacy.drug",
                        verbose_name="Препарат",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="pharmacy.warehouse",
                        verbose_name="Склад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Остатки",
                "verbose_name_plural": "Остатки на складе",
                "ordering": ["expiry_date"],
            },
        ),
    ]
