# Generated by Django 5.2.9 on 2025-12-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название показателя"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("visits", "Посещения"),
                            ("hospitalizations", "Госпитализации"),
                            ("lab_tests", "Лабораторные исследования"),
                            ("radiology", "Радиологические исследования"),
                            ("revenue", "Выручка"),
                            ("satisfaction", "Удовлетворённость пациентов"),
                            ("wait_time", "Время ожидания"),
                            ("bed_occupancy", "Загрузка коек"),
                        ],
                        max_length=20,
                        verbose_name="Тип показателя",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "unit",
                    models.CharField(max_length=50, verbose_name="Единица измерения"),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Целевое значение",
                    ),
                ),
                (
                    "calculation_method",
                    models.TextField(blank=True, verbose_name="Методика расчёта"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "KPI показатель",
                "verbose_name_plural": "KPI показатели",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название отчёта"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medical", "Медицинские"),
                            ("financial", "Финансовые"),
                            ("statistical", "Статистические"),
                            ("operational", "Операционные"),
                            ("kpi", "KPI"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "template_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Путь к шаблону"
                    ),
                ),
                ("sql_query", models.TextField(blank=True, verbose_name="SQL запрос")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Тип отчёта",
                "verbose_name_plural": "Типы отчётов",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="KPIValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Значение"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Отделение"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kpi_values",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="reports.kpiindicator",
                        verbose_name="Показатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение KPI",
                "verbose_name_plural": "Значения KPI",
                "ordering": ["-period_end"],
            },
        ),
        migrations.CreateModel(
            name="Registry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название реестра"),
                ),
                ("period_start", models.DateField(verbose_name="Начало периода")),
                ("period_end", models.DateField(verbose_name="Конец периода")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("formed", "Сформирован"),
                            ("sent", "Отправлен"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонён"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_services",
                    models.PositiveIntegerField(default=0, verbose_name="Всего услуг"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Общая сумма",
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_registries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реестр",
                "verbose_name_plural": "Реестры",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_date", models.DateField(verbose_name="Дата услуги")),
                (
                    "service_code",
                    models.CharField(max_length=50, verbose_name="Код услуги"),
                ),
                (
                    "service_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование услуги"
                    ),
                ),
                (
                    "diagnosis_code",
                    models.CharField(max_length=20, verbose_name="Код МКБ-10"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Цена"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registry_services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registry_items",
                        to="registry.patient",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "registry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reports.registry",
                        verbose_name="Реестр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция реестра",
                "verbose_name_plural": "Позиции реестра",
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало периода"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Конец периода"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Параметры"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("html", "HTML"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Формат",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="reports/", verbose_name="Файл"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сгенерировал",
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="reports.reporttype",
                        verbose_name="Тип отчёта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сгенерированный отчёт",
                "verbose_name_plural": "Сгенерированные отчёты",
                "ordering": ["-created_at"],
            },
        ),
    ]
