# Generated by Django 5.2.9 on 2025-12-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(max_length=100, verbose_name="Тип экспорта"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "records_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество записей"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Формат файла"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Экспорт данных",
                "verbose_name_plural": "Экспорты данных",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="Имя пользователя"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP адрес")),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                ("success", models.BooleanField(default=False, verbose_name="Успешно")),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Причина неудачи"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка входа",
                "verbose_name_plural": "Попытки входа",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["username", "timestamp"],
                        name="audit_login_usernam_86a7ab_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="audit_login_ip_addr_8dc769_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=100, verbose_name="Тип ресурса"),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID ресурса"
                    ),
                ),
                (
                    "access_type",
                    models.CharField(max_length=50, verbose_name="Тип доступа"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Причина доступа"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to="registry.patient",
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к мед. данным",
                "verbose_name_plural": "Доступы к мед. данным",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_acces_user_id_722938_idx",
                    ),
                    models.Index(
                        fields=["patient", "timestamp"],
                        name="audit_acces_patient_41e9eb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("read", "Просмотр"),
                            ("update", "Изменение"),
                            ("delete", "Удаление"),
                            ("login", "Вход"),
                            ("logout", "Выход"),
                            ("failed_login", "Неудачный вход"),
                            ("export", "Экспорт"),
                            ("print", "Печать"),
                        ],
                        max_length=20,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Модель"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID объекта"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=255, verbose_name="Объект"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Изменения"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, verbose_name="URL"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись аудита",
                "verbose_name_plural": "Журнал аудита",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_audit_action_2a1328_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_audit_model_n_20c0d3_idx",
                    ),
                ],
            },
        ),
    ]
