# Generated by Django 5.2.9 on 2025-12-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название отделения"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код отделения"
                    ),
                ),
                (
                    "beds_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество коек"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "floor",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Этаж"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "head_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Заведующий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отделение",
                "verbose_name_plural": "Отделения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Номер койки")),
                ("ward", models.CharField(max_length=20, verbose_name="Палата")),
                (
                    "is_occupied",
                    models.BooleanField(default=False, verbose_name="Занята"),
                ),
                (
                    "bed_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Тип койки"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="hospital.department",
                        verbose_name="Отделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Койка",
                "verbose_name_plural": "Койки",
                "ordering": ["department", "ward", "number"],
                "unique_together": {("department", "ward", "number")},
            },
        ),
        migrations.CreateModel(
            name="Hospitalization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospitalization_type",
                    models.CharField(
                        choices=[
                            ("planned", "Плановая"),
                            ("emergency", "Экстренная"),
                            ("day", "Дневной стационар"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Тип госпитализации",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирована"),
                            ("active", "В стационаре"),
                            ("discharged", "Выписан"),
                            ("transferred", "Переведён"),
                            ("deceased", "Умер"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "admission_date",
                    models.DateTimeField(verbose_name="Дата поступления"),
                ),
                (
                    "discharge_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата выписки"
                    ),
                ),
                (
                    "diagnosis_admission",
                    models.TextField(verbose_name="Диагноз при поступлении"),
                ),
                (
                    "diagnosis_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Код МКБ-10"
                    ),
                ),
                (
                    "diagnosis_clinical",
                    models.TextField(blank=True, verbose_name="Клинический диагноз"),
                ),
                (
                    "diagnosis_final",
                    models.TextField(blank=True, verbose_name="Заключительный диагноз"),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Кем направлен"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лечащий врач",
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalizations",
                        to="hospital.bed",
                        verbose_name="Койка",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizations",
                        to="hospital.department",
                        verbose_name="Отделение",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizations",
                        to="registry.patient",
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Госпитализация",
                "verbose_name_plural": "Госпитализации",
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="DischargeEpicrisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discharge_date", models.DateField(verbose_name="Дата выписки")),
                (
                    "days_in_hospital",
                    models.PositiveIntegerField(verbose_name="Койко-дней"),
                ),
                ("diagnosis_main", models.TextField(verbose_name="Основной диагноз")),
                (
                    "diagnosis_concomitant",
                    models.TextField(blank=True, verbose_name="Сопутствующий диагноз"),
                ),
                (
                    "diagnosis_complications",
                    models.TextField(blank=True, verbose_name="Осложнения"),
                ),
                (
                    "treatment_summary",
                    models.TextField(verbose_name="Проведённое лечение"),
                ),
                (
                    "condition_at_discharge",
                    models.TextField(verbose_name="Состояние при выписке"),
                ),
                ("recommendations", models.TextField(verbose_name="Рекомендации")),
                (
                    "sick_leave_info",
                    models.TextField(
                        blank=True, verbose_name="Данные о больничном листе"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата контрольного осмотра"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_epicrises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лечащий врач",
                    ),
                ),
                (
                    "hospitalization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_epicrisis",
                        to="hospital.hospitalization",
                        verbose_name="Госпитализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выписной эпикриз",
                "verbose_name_plural": "Выписные эпикризы",
            },
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Номер истории болезни"
                    ),
                ),
                (
                    "complaints",
                    models.TextField(blank=True, verbose_name="Жалобы при поступлении"),
                ),
                (
                    "anamnesis_morbi",
                    models.TextField(blank=True, verbose_name="Анамнез заболевания"),
                ),
                (
                    "anamnesis_vitae",
                    models.TextField(blank=True, verbose_name="Анамнез жизни"),
                ),
                (
                    "status_praesens",
                    models.TextField(blank=True, verbose_name="Объективный статус"),
                ),
                (
                    "status_localis",
                    models.TextField(blank=True, verbose_name="Локальный статус"),
                ),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="План лечения"),
                ),
                ("epicrisis", models.TextField(blank=True, verbose_name="Эпикриз")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "hospitalization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to="hospital.hospitalization",
                        verbose_name="Госпитализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "История болезни",
                "verbose_name_plural": "Истории болезни",
            },
        ),
        migrations.CreateModel(
            name="TemperatureSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Температура",
                    ),
                ),
                (
                    "blood_pressure_sys",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="АД систолическое"
                    ),
                ),
                (
                    "blood_pressure_dia",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="АД диастолическое"
                    ),
                ),
                (
                    "pulse",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Пульс"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ЧДД"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "diuresis",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Диурез (мл)"
                    ),
                ),
                (
                    "stool",
                    models.CharField(blank=True, max_length=50, verbose_name="Стул"),
                ),
                (
                    "fluid_intake",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Выпито жидкости (мл)"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "hospitalization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_sheets",
                        to="hospital.hospitalization",
                        verbose_name="Госпитализация",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_sheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Медсестра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Температурный лист",
                "verbose_name_plural": "Температурные листы",
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="Медикаменты"),
                ),
                ("procedures", models.TextField(blank=True, verbose_name="Процедуры")),
                (
                    "diet",
                    models.CharField(blank=True, max_length=100, verbose_name="Диета"),
                ),
                (
                    "regime",
                    models.CharField(blank=True, max_length=100, verbose_name="Режим"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_sheets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Врач",
                    ),
                ),
                (
                    "hospitalization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_sheets",
                        to="hospital.hospitalization",
                        verbose_name="Госпитализация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лист назначений",
                "verbose_name_plural": "Листы назначений",
                "ordering": ["-date"],
            },
        ),
    ]
